name: Run Python Script and Deploy HTML to GitHub Pages

on:
  schedule:
    # Runs once every day at midnight UTC
    - cron: '0 0 * * *'  
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the main branch (if applicable)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Choose your Python version

    # Step 3: Install required dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 4: Run your Python script (this will generate or modify the HTML file)
    - name: Run Python script
      run: python main.py

    # Step 5: Build the HTML content (we're assuming script.py generates index.html)
    - name: Create and prepare the HTML file for GitHub Pages
      run: |
        # Check if the index.html file was created
        ls -l index.html
        mkdir -p deploy # Create a temporary folder to store content for GitHub Pages
        cp index.html deploy/ # Copy index.html to deploy folder

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        branch: gh-pages  # The branch where GitHub Pages content is deployed
        folder: deploy  # The folder containing the generated HTML file
